server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "rj8hPmshCLpwzwkFlxDM0iQgVWz355WVyInl4Ik0VVKsEPTUfACk3OGeGu4PZzT8"
  valid-duration: 3600 # in seconds
  refreshable-duration: 3600000 # in seconds